software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

jobs:
  strapmeboots:
    builder: "make"
    software_groups: *software
    base: "quay.io/madebymany/build-bases:trusty"
    packages:
      - type: debian
        name: strapmeboots
        version: 2:0.0.12
        depends:
          - ntp
          - curl
          - htop
          - mtr-tiny
          - aptitude
          - sudo
          - vim-nox
          - gdb
          - strace
          - mxm-utils
          - runit-common
          - apt-transport-s3
          - python-aws
          - slackcat
        repos:
          - mxm-public
        target: install
