software_groups: &software
  - "base"

jobs:
  strapmeboots:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    packages:
      - type: debian
        name: strapmeboots
        version: 1:0.1.7-3
        depends:
          - ntp
          - curl
          - htop
          - mtr
          - aptitude
          - sudo
          - vim-nox
          - gdb
          - strace
          - mxm-utils
          - runit-common
          - apt-transport-s3
        repos:
          - mxm-public
        target: install
