software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: focal-unstable
    production: focal-stable

jobs:
  strapmeboots:
    builder: "make"
    software_groups: *software
    base: "quay.io/madebymany/build-bases:focal"
    promote_through:
      - focal-unstable
      - focal-stable
    packages:
      - type: debian
        name: strapmeboots
        version_epoch: 3
        depends:
          - ntp
          - curl
          - htop
          - mtr-tiny
          - aptitude
          - sudo
          - vim-nox
          - gdb
          - strace
          - mxm-utils
          - runit-common
          - apt-transport-s3
          - python-aws
          - slackcat
        repos:
          - mxm-public
        target: install
